version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8085:80"
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: oxwall
      MYSQL_USER: oxwall
      MYSQL_PASSWORD: oxwallpass
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - oxwall-db-data:/var/lib/mysql
volumes:
  oxwall-db-data: